export const AUTH_LOADING = "AUTH_LOADING";
export const LOGIN = "LOGIN";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

//user action types
export const LOADING_USER_ACTION = "LOADING_USER_ACTION";
export const USER_ACTION_FAILURE = "USER_ACTION_FAILURE";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

//admin action types
export const LOADING_ADMIN_ACTION = "LOADING_ADMIN_ACTION";
export const ADMIN_ACTION_FAILURE = "ADMIN_ACTION_FAILURE";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_PRODUCTS_LIST = "FETCH_PRODUCTS_LIST";
export const UPDATE_PRODUCT_DETAILS = "UPDATE_PRODUCT_DETAILS";